_wandb:
    value:
        cli_version: 0.28.1
        e:
            f89hvp2drd9gpycstshguaixy91s83g9:
                codePath: transpressor.py
                codePathLocal: transpressor.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "137438953472"
                        used: "81442455552"
                email: anuragkompalli01@gmail.com
                executable: /workspace/le-wm/.venv/bin/python3
                git:
                    commit: 3d335269925a53ec1cf1604e5f5b279000b83ed1
                    remote: https://github.com/kompalan/le-wm.git
                gpu: NVIDIA GeForce RTX 5060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 4608
                      memoryTotal: "17103323136"
                      name: NVIDIA GeForce RTX 5060 Ti
                      uuid: GPU-fc5af21c-fe16-140a-d91f-f2e0085d1a19
                host: 54fec542bae7
                memory:
                    total: "270061260800"
                os: Linux-6.8.0-107-generic-x86_64-with-glibc2.39
                program: /workspace/le-wm/transpressor.py
                python: CPython 3.12.13
                root: .
                startedAt: "2026-07-28T02:35:42.162154Z"
                writerId: f89hvp2drd9gpycstshguaixy91s83g9
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 50
                - 51
                - 53
                - 63
                - 79
                - 106
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 50
                - 51
                - 53
                - 63
                - 79
                - 106
            "3":
                - 7
                - 13
                - 41
                - 66
            "4": 3.12.13
            "5": 0.28.1
            "6": 5.14.1
            "12": 0.28.1
            "13": linux-x86_64
action_dim:
    value: 2
data:
    value:
        dataset:
            frameskip: 1
            keys_to_cache:
                - action
                - proprio
                - state
            keys_to_load:
                - pixels
                - action
                - proprio
                - state
            name: pusht_expert_train.h5
            num_steps: ${eval:'${num_preds} + ${history_size}'}
embed_dim:
    value: 192
history_size:
    value: 5
img_size:
    value: 224
loader:
    value:
        batch_size: 128
        num_workers: ${num_workers}
        persistent_workers: true
        pin_memory: true
        prefetch_factor: 3
loss:
    value:
        sigreg:
            kwargs:
                knots: 17
                num_proj: 1024
            weight: 0.09
model:
    value:
        _target_: transpressor.Transpressor
        depth: 6
        dim_head: 64
        dropout: 0.1
        heads: 16
        hidden_dim: ${embed_dim}
        input_dim: ${action_dim}
        mlp_dim: 2048
        output_dim: ${action_dim}
num_preds:
    value: 1
num_workers:
    value: 6
optimizer:
    value:
        lr: 5e-05
        type: AdamW
        weight_decay: 0.001
output_model_name:
    value: transpressor
seed:
    value: 3072
slurm.job_id:
    value: N/A
slurm.task_id:
    value: N/A
subdir:
    value: ${hydra:job.id}
system.working_dir:
    value: /workspace/le-wm
train_split:
    value: 0.9
trainer:
    value:
        accelerator: gpu
        devices: auto
        gradient_clip_val: 1
        max_epochs: 100
        precision: 64
wandb:
    value:
        config:
            entity: anuragkompalli
            id: ${subdir}
            log_model: false
            name: ${output_model_name}
            project: transpressor
            resume: allow
        enabled: true
